// GlobalPuppies — Seed Script (plain ESM, no TypeScript needed)
// Run with: node scripts/seed.mjs

import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "crypto";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// Load .env.local manually
const __dirname = dirname(fileURLToPath(import.meta.url));
const envPath = join(__dirname, "../.env.local");
try {
  const envFile = readFileSync(envPath, "utf-8");
  envFile.split("\n").forEach((line) => {
    const [key, ...rest] = line.split("=");
    if (key && rest.length) {
      process.env[key.trim()] = rest.join("=").trim();
    }
  });
  console.log("Loaded .env.local");
} catch {
  console.log("No .env.local found, using existing env vars");
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY",
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const PUPPIES = [
  {
    name: "Bella",
    breed: "Golden Retriever",
    age_weeks: 8,
    price: 1800,
    gender: "Female",
    color: "Golden",
    weight_lbs: 4.2,
    description:
      "Bella is a sweet and affectionate Golden Retriever puppy. She loves cuddles, playtime, and is already beginning leash training. Extremely friendly with children and other pets.",
    image_url:
      "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Friendly", "Intelligent", "Playful"],
  },
  {
    name: "Max",
    breed: "French Bulldog",
    age_weeks: 10,
    price: 3500,
    gender: "Male",
    color: "Brindle",
    weight_lbs: 3.8,
    description:
      "Max is a charming French Bulldog with a playful personality. He has a wonderful temperament and gets along great with people of all ages.",
    image_url:
      "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Calm", "Affectionate", "Alert", "Easygoing"],
  },
  {
    name: "Luna",
    breed: "Siberian Husky",
    age_weeks: 9,
    price: 2200,
    gender: "Female",
    color: "Gray & White",
    weight_lbs: 5.1,
    description:
      "Luna is a stunning Siberian Husky with piercing blue eyes. She is energetic, loves outdoor adventures, and is highly intelligent.",
    image_url:
      "https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Energetic", "Outgoing", "Friendly", "Alert"],
  },
  {
    name: "Charlie",
    breed: "Labrador Retriever",
    age_weeks: 8,
    price: 1600,
    gender: "Male",
    color: "Black",
    weight_lbs: 4.8,
    description:
      "Charlie is an incredibly friendly black Labrador. He is eager to learn, loves swimming, and is excellent with families.",
    image_url:
      "https://images.unsplash.com/photo-1591856954575-e5c6b3dad23e?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Friendly", "Active", "Outgoing", "Trusting"],
  },
  {
    name: "Daisy",
    breed: "Poodle",
    age_weeks: 11,
    price: 2800,
    gender: "Female",
    color: "White",
    weight_lbs: 2.9,
    description:
      "Daisy is an elegant Toy Poodle with a hypoallergenic coat. She is brilliantly smart, easy to train, and simply adores being the center of attention.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Intelligent", "Active", "Alert", "Faithful"],
  },
  {
    name: "Cooper",
    breed: "Beagle",
    age_weeks: 9,
    price: 1400,
    gender: "Male",
    color: "Tri-Color",
    weight_lbs: 3.5,
    description:
      "Cooper is a classic Beagle with a big personality. He is curious, cheerful, and loves exploring the great outdoors.",
    image_url:
      "https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Curious", "Friendly", "Merry", "Independent"],
  },
  {
    name: "Zoe",
    breed: "Yorkshire Terrier",
    age_weeks: 10,
    price: 2000,
    gender: "Female",
    color: "Tan & Blue",
    weight_lbs: 1.8,
    description:
      "Zoe is a tiny but bold Yorkie with a gorgeous silky coat. She is confident, lively, and loves being pampered.",
    image_url:
      "https://images.unsplash.com/photo-1612195583950-b8fd34c87093?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Feisty", "Bold", "Confident", "Intelligent"],
  },
  {
    name: "Buddy",
    breed: "German Shepherd",
    age_weeks: 8,
    price: 2400,
    gender: "Male",
    color: "Black & Tan",
    weight_lbs: 5.6,
    description:
      "Buddy is a noble German Shepherd puppy with exceptional intelligence. He is loyal, protective, and excels in obedience training.",
    image_url:
      "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Courageous", "Intelligent", "Obedient"],
  },
  {
    name: "Molly",
    breed: "Cavalier King Charles Spaniel",
    age_weeks: 9,
    price: 2600,
    gender: "Female",
    color: "Blenheim",
    weight_lbs: 3.2,
    description:
      "Molly is breathtakingly beautiful with the sweetest nature. She is gentle with children, loving with strangers, and absolutely lives for cuddles.",
    image_url:
      "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Affectionate", "Graceful", "Sociable"],
  },
  {
    name: "Rocky",
    breed: "Rottweiler",
    age_weeks: 8,
    price: 2200,
    gender: "Male",
    color: "Black & Mahogany",
    weight_lbs: 7.2,
    description:
      "Rocky is a powerful and devoted Rottweiler puppy. Despite his large build, he is gentle with family members and naturally confident.",
    image_url:
      "https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Devoted", "Courageous", "Confident"],
  },
  {
    name: "Lola",
    breed: "Shih Tzu",
    age_weeks: 10,
    price: 1800,
    gender: "Female",
    color: "Gold & White",
    weight_lbs: 2.4,
    description:
      "Lola is a glamorous Shih Tzu with a flowing coat and big personality. She is sweet-natured and loves lap time.",
    image_url:
      "https://images.unsplash.com/photo-1617898700578-5c1e76ede77c?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Affectionate", "Playful", "Outgoing", "Lively"],
  },
  {
    name: "Bear",
    breed: "Chow Chow",
    age_weeks: 11,
    price: 2800,
    gender: "Male",
    color: "Red",
    weight_lbs: 6.4,
    description:
      "Bear is a majestic Chow Chow with a lion-like mane and dignified presence. He is loyal to his family and has a calm, independent personality.",
    image_url:
      "https://images.unsplash.com/photo-1523567830207-96731740fa71?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Independent", "Quiet", "Aloof"],
  },
  {
    name: "Sadie",
    breed: "Border Collie",
    age_weeks: 8,
    price: 1900,
    gender: "Female",
    color: "Black & White",
    weight_lbs: 4.1,
    description:
      "Sadie is an incredibly intelligent Border Collie puppy. She is agile, eager to please, and excels at learning new commands.",
    image_url:
      "https://images.unsplash.com/photo-1629740067891-12a58af4e802?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Intelligent", "Energetic", "Responsive", "Alert"],
  },
  {
    name: "Duke",
    breed: "Great Dane",
    age_weeks: 9,
    price: 2000,
    gender: "Male",
    color: "Fawn",
    weight_lbs: 9.3,
    description:
      "Duke is a gentle giant Great Dane puppy. He is friendly, patient, and will grow into one of the most majestic dogs.",
    image_url:
      "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Friendly", "Patient", "Dependable", "Gentle"],
  },
  {
    name: "Stella",
    breed: "Australian Shepherd",
    age_weeks: 8,
    price: 2100,
    gender: "Female",
    color: "Blue Merle",
    weight_lbs: 4.6,
    description:
      "Stella is a strikingly beautiful Australian Shepherd with captivating merle coloring. She is athletic, intelligent, and endlessly enthusiastic.",
    image_url:
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Energetic", "Intelligent", "Versatile", "Responsive"],
  },
  {
    name: "Tucker",
    breed: "Dachshund",
    age_weeks: 10,
    price: 1500,
    gender: "Male",
    color: "Red",
    weight_lbs: 2.1,
    description:
      "Tucker is a lovable miniature Dachshund with a long body and big heart. He is curious, clever, and fiercely devoted to his family.",
    image_url:
      "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Clever", "Stubborn", "Devoted", "Lively"],
  },
  {
    name: "Chloe",
    breed: "Maltese",
    age_weeks: 9,
    price: 2400,
    gender: "Female",
    color: "White",
    weight_lbs: 1.5,
    description:
      "Chloe is an exquisite Maltese with a pristine white coat and gentle eyes. She is affectionate, fearless, and loves being center of attention.",
    image_url:
      "https://images.unsplash.com/photo-1534361960057-19f4434a337d?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Playful", "Fearless", "Affectionate"],
  },
  {
    name: "Zeus",
    breed: "Doberman Pinscher",
    age_weeks: 8,
    price: 2500,
    gender: "Male",
    color: "Black & Rust",
    weight_lbs: 6.8,
    description:
      "Zeus is an elegant and alert Doberman puppy. He is highly trainable, loyal, and will grow into a noble guardian.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Alert", "Loyal", "Fearless", "Energetic"],
  },
  {
    name: "Nala",
    breed: "Bernese Mountain Dog",
    age_weeks: 9,
    price: 2900,
    gender: "Female",
    color: "Tricolor",
    weight_lbs: 8.1,
    description:
      "Nala is a fluffy and gentle Bernese Mountain Dog. She is calm, good-natured, and will become an incredibly loyal family companion.",
    image_url:
      "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Calm", "Affectionate", "Loyal", "Patient"],
  },
  {
    name: "Archie",
    breed: "Pug",
    age_weeks: 10,
    price: 1700,
    gender: "Male",
    color: "Fawn",
    weight_lbs: 3.2,
    description:
      "Archie is a charming Pug with an irresistible wrinkled face. He is sociable, mischievous, and has a wonderful comedic streak.",
    image_url:
      "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Charming", "Mischievous", "Sociable", "Loving"],
  },
  {
    name: "Rosie",
    breed: "Cocker Spaniel",
    age_weeks: 8,
    price: 1900,
    gender: "Female",
    color: "Golden Buff",
    weight_lbs: 3.7,
    description:
      "Rosie is a gorgeous Cocker Spaniel with silky long ears and a happy wagging tail. She is cheerful, gentle, and adores playtime.",
    image_url:
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Cheerful", "Gentle", "Faithful", "Trainable"],
  },
  {
    name: "Milo",
    breed: "Chihuahua",
    age_weeks: 12,
    price: 1200,
    gender: "Male",
    color: "Chocolate",
    weight_lbs: 0.9,
    description:
      "Milo is a tiny Chihuahua with an enormous personality. He is bold, lively, and extremely devoted to his owner.",
    image_url:
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Bold", "Devoted", "Alert", "Sassy"],
  },
  {
    name: "Penny",
    breed: "Boxer",
    age_weeks: 8,
    price: 2000,
    gender: "Female",
    color: "Brindle",
    weight_lbs: 5.9,
    description:
      "Penny is an energetic Boxer puppy with boundless enthusiasm. She is loyal, playful, and wonderful with children.",
    image_url:
      "https://images.unsplash.com/photo-1616210229800-1e65e07f3284?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Playful", "Devoted", "Loyal", "Energetic"],
  },
  {
    name: "Oliver",
    breed: "Pomeranian",
    age_weeks: 10,
    price: 2200,
    gender: "Male",
    color: "Orange",
    weight_lbs: 1.4,
    description:
      "Oliver is a fluffy Pomeranian ball of energy. He is vivacious, intelligent, and has a personality much bigger than his tiny body.",
    image_url:
      "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Vivacious", "Bold", "Intelligent", "Friendly"],
  },
  {
    name: "Sophie",
    breed: "Havanese",
    age_weeks: 9,
    price: 2600,
    gender: "Female",
    color: "Cream",
    weight_lbs: 2.3,
    description:
      "Sophie is a silky Havanese with a happy-go-lucky personality. She is social, trainable, and brings joy to everyone she meets.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Sociable", "Playful", "Intelligent", "Gentle"],
  },
  {
    name: "Atlas",
    breed: "Saint Bernard",
    age_weeks: 8,
    price: 2400,
    gender: "Male",
    color: "Red & White",
    weight_lbs: 10.5,
    description:
      "Atlas is a massive and lovable Saint Bernard puppy. He is patient, gentle, and will grow into a wonderful gentle giant.",
    image_url:
      "https://images.unsplash.com/photo-1551730459-82e77c537e56?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Patient", "Friendly", "Obedient"],
  },
  {
    name: "Ivy",
    breed: "Shiba Inu",
    age_weeks: 10,
    price: 2800,
    gender: "Female",
    color: "Red Sesame",
    weight_lbs: 3.6,
    description:
      "Ivy is a spirited Shiba Inu with a fox-like face and confident attitude. She is bold, independent, and fiercely loyal.",
    image_url:
      "https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Confident", "Bold", "Spirited", "Loyal"],
  },
  {
    name: "Bruno",
    breed: "Basset Hound",
    age_weeks: 9,
    price: 1600,
    gender: "Male",
    color: "Tri-Color",
    weight_lbs: 5.3,
    description:
      "Bruno is an adorable Basset Hound with the world longest ears. He is laid-back, friendly, and has an incredible nose.",
    image_url:
      "https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Laid-back", "Friendly", "Gentle", "Devoted"],
  },
  {
    name: "Ellie",
    breed: "Bichon Frise",
    age_weeks: 11,
    price: 2100,
    gender: "Female",
    color: "White",
    weight_lbs: 2.0,
    description:
      "Ellie is a powder-puff Bichon Frise with a cheerful personality. She is hypoallergenic, friendly, and never fails to make people smile.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Cheerful", "Playful", "Gentle", "Curious"],
  },
  {
    name: "Thor",
    breed: "Alaskan Malamute",
    age_weeks: 8,
    price: 2300,
    gender: "Male",
    color: "Gray & White",
    weight_lbs: 8.9,
    description:
      "Thor is a powerful and majestic Alaskan Malamute. He is affectionate with family, strong, and loves cold-weather activities.",
    image_url:
      "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Playful", "Friendly", "Dignified"],
  },
  {
    name: "Lily",
    breed: "Pomsky",
    age_weeks: 9,
    price: 3200,
    gender: "Female",
    color: "White & Gray",
    weight_lbs: 2.8,
    description:
      "Lily is an incredibly adorable Pomsky — a perfect blend of Pomeranian and Husky with stunning looks.",
    image_url:
      "https://images.unsplash.com/photo-1592754862816-1a21a4ea2281?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "Designer",
    temperament: ["Playful", "Energetic", "Intelligent", "Affectionate"],
  },
  {
    name: "Finn",
    breed: "Irish Setter",
    age_weeks: 8,
    price: 1800,
    gender: "Male",
    color: "Mahogany Red",
    weight_lbs: 5.2,
    description:
      "Finn is a stunning Irish Setter with a flowing mahogany coat. He is exuberant, affectionate, and bursting with zest for life.",
    image_url:
      "https://images.unsplash.com/photo-1600077106724-946750eeaf3c?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Energetic", "Friendly", "Affectionate", "Independent"],
  },
  {
    name: "Ginger",
    breed: "Akita",
    age_weeks: 9,
    price: 2700,
    gender: "Female",
    color: "Red Fawn",
    weight_lbs: 7.1,
    description:
      "Ginger is a dignified Akita with a noble character. She is deeply loyal to her family and has a calm, confident presence.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Courageous", "Dignified", "Calm"],
  },
  {
    name: "Hugo",
    breed: "English Bulldog",
    age_weeks: 10,
    price: 3800,
    gender: "Male",
    color: "White & Brindle",
    weight_lbs: 5.4,
    description:
      "Hugo is an endearingly wrinkled English Bulldog with a heart of gold. He is calm, courageous, and absolutely loves people.",
    image_url:
      "https://images.unsplash.com/photo-1454023989775-79520f04e0fa?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Calm", "Courageous", "Friendly", "Loyal"],
  },
  {
    name: "Aurora",
    breed: "Samoyed",
    age_weeks: 9,
    price: 3100,
    gender: "Female",
    color: "White",
    weight_lbs: 5.8,
    description:
      "Aurora is a breathtaking Samoyed with a stunning white coat and the famous Samoyed smile. She is gentle, loving, and radiant.",
    image_url:
      "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Friendly", "Adaptable", "Playful"],
  },
  {
    name: "Rex",
    breed: "Dalmatian",
    age_weeks: 8,
    price: 1700,
    gender: "Male",
    color: "White & Black",
    weight_lbs: 4.7,
    description:
      "Rex is a classically spotted Dalmatian full of energy and enthusiasm. He is active, intelligent, and loves being part of an active family.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Energetic", "Outgoing", "Playful", "Sensitive"],
  },
  {
    name: "Jasper",
    breed: "Welsh Corgi Pembroke",
    age_weeks: 9,
    price: 2300,
    gender: "Male",
    color: "Sable & White",
    weight_lbs: 3.4,
    description:
      "Jasper is an adorable Pembroke Welsh Corgi with iconic stubby legs and alert ears. He is smart, tenacious, and endlessly entertaining.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Smart", "Alert", "Tenacious", "Friendly"],
  },
  {
    name: "Amber",
    breed: "Miniature Schnauzer",
    age_weeks: 10,
    price: 1800,
    gender: "Female",
    color: "Salt & Pepper",
    weight_lbs: 2.6,
    description:
      "Amber is a spirited Mini Schnauzer with a distinguished beard. She is fearless, friendly, and learns new things remarkably fast.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Spirited", "Friendly", "Alert", "Trainable"],
  },
  {
    name: "Apollo",
    breed: "Bloodhound",
    age_weeks: 8,
    price: 1700,
    gender: "Male",
    color: "Black & Tan",
    weight_lbs: 8.6,
    description:
      "Apollo is a wrinkled and lovable Bloodhound with a nose unmatched in the animal kingdom. He is tenacious on the trail but gentle at home.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Affectionate", "Tenacious", "Even-tempered"],
  },
  {
    name: "Storm",
    breed: "Belgian Malinois",
    age_weeks: 8,
    price: 2600,
    gender: "Male",
    color: "Fawn & Black",
    weight_lbs: 5.9,
    description:
      "Storm is an elite Belgian Malinois puppy. Preferred by military and police forces, he is driven, intelligent, and fiercely loyal.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Driven", "Intelligent", "Loyal", "Confident"],
  },
  {
    name: "Ace",
    breed: "Cane Corso",
    age_weeks: 8,
    price: 2800,
    gender: "Male",
    color: "Black",
    weight_lbs: 10.4,
    description:
      "Ace is a commanding Cane Corso with a regal presence. He is intelligent, loyal, and will grow into a magnificent protector.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Intelligent", "Loyal", "Stable", "Protective"],
  },
  {
    name: "Blaze",
    breed: "Rhodesian Ridgeback",
    age_weeks: 8,
    price: 2100,
    gender: "Male",
    color: "Wheaten",
    weight_lbs: 6.8,
    description:
      "Blaze is a muscular Rhodesian Ridgeback with the signature ridge along his back. He is dignified and strongly devoted to his family.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Dignified", "Mischievous", "Loyal", "Strong"],
  },
  {
    name: "Hercules",
    breed: "English Mastiff",
    age_weeks: 8,
    price: 2700,
    gender: "Male",
    color: "Apricot",
    weight_lbs: 13.8,
    description:
      "Hercules is a magnificent English Mastiff puppy. Despite his enormous frame, he is incredibly gentle, loving, and a natural protector.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Loving", "Courageous", "Calm"],
  },
  {
    name: "Flora",
    breed: "West Highland Terrier",
    age_weeks: 10,
    price: 1800,
    gender: "Female",
    color: "White",
    weight_lbs: 2.8,
    description:
      "Flora is a confident and perky Westie with a bright white coat and cheeky personality. She is self-assured and absolutely loves life.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Confident", "Alert", "Friendly", "Self-assured"],
  },
  {
    name: "Iris",
    breed: "Standard Poodle",
    age_weeks: 9,
    price: 2500,
    gender: "Female",
    color: "Apricot",
    weight_lbs: 5.3,
    description:
      "Iris is an exceptionally intelligent Standard Poodle with an elegant apricot coat. She excels in obedience and is wonderfully hypoallergenic.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Intelligent", "Active", "Elegant", "Faithful"],
  },
  {
    name: "Willow",
    breed: "Shetland Sheepdog",
    age_weeks: 10,
    price: 1900,
    gender: "Female",
    color: "Sable & White",
    weight_lbs: 3.1,
    description:
      "Willow is a beautiful and responsive Sheltie. She is incredibly quick to learn, deeply devoted, and has an elegant long coat.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Intelligent", "Responsive", "Devoted", "Alert"],
  },
  {
    name: "Caesar",
    breed: "Bullmastiff",
    age_weeks: 9,
    price: 2300,
    gender: "Male",
    color: "Fawn",
    weight_lbs: 9.7,
    description:
      "Caesar is a powerful Bullmastiff puppy with a fearless presence. He is docile with family, reliable under pressure, and a natural guardian.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Fearless", "Docile", "Loyal", "Reliable"],
  },
  {
    name: "Sultan",
    breed: "Tibetan Mastiff",
    age_weeks: 8,
    price: 4500,
    gender: "Male",
    color: "Black & Gold",
    weight_lbs: 14.2,
    description:
      "Sultan is a magnificent Tibetan Mastiff — the ancient guardian of the Himalayas. He is regal, independent, and commands the most formidable presence.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Aloof", "Loyal", "Protective", "Independent"],
  },
  {
    name: "Athena",
    breed: "Great Pyrenees",
    age_weeks: 8,
    price: 2200,
    gender: "Female",
    color: "White",
    weight_lbs: 9.4,
    description:
      "Athena is a majestic Great Pyrenees with a cloud-white double coat. She is patient, devoted, and has spent millennia protecting flocks.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Patient", "Devoted", "Calm", "Confident"],
  },
  {
    name: "Honey",
    breed: "Golden Retriever",
    age_weeks: 9,
    price: 1900,
    gender: "Female",
    color: "Light Golden",
    weight_lbs: 4.5,
    description:
      "Honey is a light golden beauty with a luminous coat. She is devoted, obedient, and embodies everything that makes Goldens so beloved.",
    image_url:
      "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Devoted", "Patient", "Reliable", "Friendly"],
  },
  {
    name: "Ghost",
    breed: "White Swiss Shepherd",
    age_weeks: 8,
    price: 2400,
    gender: "Male",
    color: "Pure White",
    weight_lbs: 6.1,
    description:
      "Ghost is a breathtaking White Swiss Shepherd — elegant, intelligent, and deeply devoted. His pure white coat makes him truly unforgettable.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "FCI",
    temperament: ["Loyal", "Intelligent", "Calm", "Attentive"],
  },
  {
    name: "Bravo",
    breed: "Portuguese Water Dog",
    age_weeks: 8,
    price: 2600,
    gender: "Male",
    color: "Black & White",
    weight_lbs: 4.7,
    description:
      "Bravo is an athletic Portuguese Water Dog with a curly, hypoallergenic coat. He is obedient, spirited, and an exceptional swimmer.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Obedient", "Spirited", "Athletic", "Loyal"],
  },
  {
    name: "Phoenix",
    breed: "Labrador Retriever",
    age_weeks: 8,
    price: 1700,
    gender: "Male",
    color: "Yellow",
    weight_lbs: 5.0,
    description:
      "Phoenix is a sunny yellow Labrador with irresistible charm. He is friendly, athletic, and excels as a family dog or sporting companion.",
    image_url:
      "https://images.unsplash.com/photo-1591856954575-e5c6b3dad23e?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Friendly", "Active", "Gentle", "Outgoing"],
  },
  {
    name: "Meadow",
    breed: "Borzoi",
    age_weeks: 9,
    price: 2500,
    gender: "Female",
    color: "White & Cream",
    weight_lbs: 5.9,
    description:
      "Meadow is a graceful Borzoi with aristocratic bearing and silky flowing coat. She is gentle, affectionate, and moves with incredible grace.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Athletic", "Affectionate", "Independent"],
  },
  {
    name: "Pumpkin",
    breed: "Norwich Terrier",
    age_weeks: 11,
    price: 2000,
    gender: "Female",
    color: "Red",
    weight_lbs: 2.5,
    description:
      "Pumpkin is a bold and fearless Norwich Terrier — small in body, giant in spirit. She is affectionate, adaptable, and endlessly lovable.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Fearless", "Affectionate", "Spirited", "Adaptable"],
  },
  {
    name: "Biscuit",
    breed: "Cairn Terrier",
    age_weeks: 10,
    price: 1700,
    gender: "Male",
    color: "Wheaten",
    weight_lbs: 2.8,
    description:
      "Biscuit is a Cairn Terrier — the same breed as Toto from Wizard of Oz. He is fearless, loyal, and packed with personality.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Fearless", "Alert", "Loyal", "Spirited"],
  },
  {
    name: "Maple",
    breed: "Nova Scotia Duck Tolling Retriever",
    age_weeks: 8,
    price: 2400,
    gender: "Female",
    color: "Red",
    weight_lbs: 4.3,
    description:
      "Maple is a vivacious Toller with a stunning red coat. She is cunning, alert, and has a fascinating tolling instinct near water.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Alert", "Intelligent", "Outgoing", "Trainable"],
  },
  {
    name: "Nugget",
    breed: "Boykin Spaniel",
    age_weeks: 9,
    price: 1800,
    gender: "Male",
    color: "Chocolate Brown",
    weight_lbs: 4.1,
    description:
      "Nugget is a cheerful Boykin Spaniel — South Carolina state dog. He is friendly, energetic, and an exceptional hunting companion.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Friendly", "Energetic", "Lovable", "Trainable"],
  },
  {
    name: "Electra",
    breed: "Keeshond",
    age_weeks: 10,
    price: 2000,
    gender: "Female",
    color: "Gray & Cream",
    weight_lbs: 4.8,
    description:
      "Electra is a fluffy Keeshond with a spectacular spectacled face. She is smart, friendly, and one of the most charming dogs imaginable.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Friendly", "Outgoing", "Alert", "Agile"],
  },
  {
    name: "Titan",
    breed: "Kangal",
    age_weeks: 8,
    price: 3000,
    gender: "Male",
    color: "Fawn",
    weight_lbs: 11.2,
    description:
      "Titan is a majestic Kangal puppy — the premier livestock guardian dog. He is calm, controlled, and will grow into a formidable protector.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "UKC",
    temperament: ["Calm", "Controlled", "Loyal", "Protective"],
  },
  {
    name: "Hera",
    breed: "Caucasian Shepherd",
    age_weeks: 8,
    price: 3500,
    gender: "Female",
    color: "Gray & White",
    weight_lbs: 13.5,
    description:
      "Hera is a powerful Caucasian Shepherd of ancient mountain guardian heritage. She is fearless, deeply loyal, and an extraordinary natural protector.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "FCI",
    temperament: ["Fearless", "Loyal", "Strong-willed", "Protective"],
  },
  {
    name: "Nimbus",
    breed: "Lagotto Romagnolo",
    age_weeks: 9,
    price: 3200,
    gender: "Male",
    color: "White & Brown",
    weight_lbs: 4.0,
    description:
      "Nimbus is an adorable Lagotto — the Italian truffle dog. He is keen-nosed, energetic, and has a wonderful woolly teddy-bear coat.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Keen", "Active", "Loyal", "Trainable"],
  },
  {
    name: "Clover",
    breed: "Biewer Terrier",
    age_weeks: 11,
    price: 2700,
    gender: "Female",
    color: "Blue White Gold",
    weight_lbs: 1.2,
    description:
      "Clover is a rare and exquisite Biewer Terrier with a stunning tricolor coat. She is playful, devoted, and surprisingly bold.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Devoted", "Playful", "Bold", "Friendly"],
  },
  {
    name: "Magnus",
    breed: "Norwegian Elkhound",
    age_weeks: 8,
    price: 2000,
    gender: "Male",
    color: "Gray",
    weight_lbs: 5.4,
    description:
      "Magnus is a proud Norwegian Elkhound — an ancient Viking breed. He is bold, playful, and has a thick double coat made for cold winters.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Bold", "Energetic", "Playful", "Loyal"],
  },
  {
    name: "Cleopatra",
    breed: "Saluki",
    age_weeks: 10,
    price: 3000,
    gender: "Female",
    color: "Cream",
    weight_lbs: 4.8,
    description:
      "Cleopatra is a regal Saluki — the Royal Dog of Egypt. She is gentle, deeply affectionate, and possesses one of the most ancient pedigrees in dogdom.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Aloof", "Faithful", "Reserved"],
  },
  {
    name: "Astro",
    breed: "Giant Schnauzer",
    age_weeks: 8,
    price: 2500,
    gender: "Male",
    color: "Black",
    weight_lbs: 8.3,
    description:
      "Astro is a powerful Giant Schnauzer with a dominant personality. He is intelligent, loyal, and requires an experienced owner who matches his energy.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Intelligent", "Bold", "Trainable"],
  },
  {
    name: "Duchess",
    breed: "Brussels Griffon",
    age_weeks: 11,
    price: 2800,
    gender: "Female",
    color: "Red",
    weight_lbs: 1.7,
    description:
      "Duchess is a little Griffon with an almost human-like face and enormous personality. She is sensitive, curious, and forms a deep bond with her person.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Sensitive", "Curious", "Alert", "Self-important"],
  },
  {
    name: "Sage",
    breed: "Icelandic Sheepdog",
    age_weeks: 9,
    price: 2400,
    gender: "Female",
    color: "Cream & White",
    weight_lbs: 4.2,
    description:
      "Sage is a cheerful Icelandic Sheepdog — Iceland only native breed. She is curious, energetic, and has a playful herding instinct.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Cheerful", "Curious", "Energetic", "Friendly"],
  },
  {
    name: "Baron",
    breed: "Leonberger",
    age_weeks: 8,
    price: 2800,
    gender: "Male",
    color: "Lion Yellow",
    weight_lbs: 11.6,
    description:
      "Baron is a stunning Leonberger resembling a small lion. He is gentle, patient, and will become a magnificent loyal companion.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Gentle", "Patient", "Obedient", "Loyal"],
  },
  {
    name: "Ember",
    breed: "Eurasier",
    age_weeks: 10,
    price: 2600,
    gender: "Female",
    color: "Red",
    weight_lbs: 5.7,
    description:
      "Ember is a harmoniously balanced Eurasier with a beautiful plush coat. She is calm, reserved with strangers but deeply affectionate with her family.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "FCI",
    temperament: ["Calm", "Self-assured", "Even-tempered", "Loyal"],
  },
  {
    name: "Harley",
    breed: "Flat-Coated Retriever",
    age_weeks: 9,
    price: 1900,
    gender: "Male",
    color: "Liver",
    weight_lbs: 5.6,
    description:
      "Harley is an eternally youthful Flat-Coat with a wagging tail and exuberant spirit. He is optimistic, cheerful, and known as the Peter Pan of dogs.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Outgoing", "Cheerful", "Optimistic", "Playful"],
  },
  {
    name: "Coral",
    breed: "Basenji",
    age_weeks: 10,
    price: 2300,
    gender: "Female",
    color: "Chestnut & White",
    weight_lbs: 3.2,
    description:
      "Coral is a fascinating Basenji — the barkless dog of Africa. She is graceful, alert, and has the cat-like cleanliness of a true ancient breed.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Alert", "Energetic", "Playful", "Poised"],
  },
  {
    name: "Hunter",
    breed: "Pointer",
    age_weeks: 9,
    price: 1600,
    gender: "Male",
    color: "Liver & White",
    weight_lbs: 5.0,
    description:
      "Hunter is a classic English Pointer — born to hunt, bred to love. He is hardworking, kind-natured, and exceptionally athletic.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Hardworking", "Kind", "Energetic", "Loyal"],
  },
  {
    name: "King",
    breed: "Boerboel",
    age_weeks: 8,
    price: 2900,
    gender: "Male",
    color: "Tawny",
    weight_lbs: 13.1,
    description:
      "King is a giant Boerboel from South Africa — a natural farm guardian. He is confident, obedient, and deeply devoted to his family.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Confident", "Obedient", "Loyal", "Protective"],
  },
  {
    name: "Poppy",
    breed: "Pekingese",
    age_weeks: 12,
    price: 1700,
    gender: "Female",
    color: "Golden",
    weight_lbs: 2.3,
    description:
      "Poppy is an imperial Pekingese with a lion-dog personality. She is dignified, regal, and has been winning hearts for thousands of years.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Affectionate", "Loyal", "Regal", "Independent"],
  },
  {
    name: "Violet",
    breed: "Papillon",
    age_weeks: 11,
    price: 1900,
    gender: "Female",
    color: "White & Sable",
    weight_lbs: 1.3,
    description:
      "Violet is a dainty Papillon with butterfly-wing ears and a brilliant mind. She is alert, friendly, and one of the most trainable toy breeds.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Alert", "Friendly", "Energetic", "Intelligent"],
  },
  {
    name: "Pixie",
    breed: "Affenpinscher",
    age_weeks: 11,
    price: 2100,
    gender: "Female",
    color: "Black",
    weight_lbs: 1.6,
    description:
      "Pixie is a monkey-faced Affenpinscher with an enormous personality packed into a tiny body. She is curious, fearless, and endlessly entertaining.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: false,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Curious", "Fearless", "Active", "Stubborn"],
  },
  {
    name: "Cosmo",
    breed: "Azawakh",
    age_weeks: 10,
    price: 3400,
    gender: "Male",
    color: "Sand",
    weight_lbs: 4.3,
    description:
      "Cosmo is an exotic Azawakh from West Africa — one of the rarest dogs in the world. He is elegant, swift, and deeply bonded to a select few.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Loyal", "Aloof", "Athletic", "Alert"],
  },
  {
    name: "Seraphina",
    breed: "Xoloitzcuintli",
    age_weeks: 9,
    price: 3500,
    gender: "Female",
    color: "Dark Bronze",
    weight_lbs: 3.3,
    description:
      "Seraphina is a rare hairless Xolo — an ancient dog of the Aztecs. She is calm, attentive, and has been a loyal companion for 3,000 years.",
    image_url:
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    is_available: true,
    is_vaccinated: true,
    is_microchipped: true,
    health_certificate: true,
    registration: "AKC",
    temperament: ["Calm", "Alert", "Loyal", "Primitive"],
  },
];

const seed = async () => {
  console.log(`Seeding ${PUPPIES.length} puppies into Supabase...`);

  const now = new Date().toISOString();
  const records = PUPPIES.map((p) => ({
    ...p,
    id: randomUUID(),
    created_at: now,
    updated_at: now,
  }));

  // Insert in batches of 20 to avoid payload limits
  const BATCH = 20;
  let inserted = 0;
  for (let i = 0; i < records.length; i += BATCH) {
    const batch = records.slice(i, i + BATCH);
    const { error } = await supabase.from("puppies").insert(batch);
    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
      process.exit(1);
    }
    inserted += batch.length;
    console.log(`Inserted ${inserted}/${records.length}...`);
  }

  console.log(`\nDone! Successfully seeded ${inserted} puppies.`);
  process.exit(0);
};

seed();
